# Generated by Django 3.0 on 2020-04-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='category',
            field=models.CharField(blank=True, choices=[('Владелец', 'Владелец'), ('Персонал', 'Персонал'), ('Клиент', 'Клиент')], max_length=64, null=True, verbose_name='Категория пользователя'),
        ),
    ]
