# Generated by Django 3.0 on 2020-03-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='category',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Doctor', 'Doctor'), ('Client', 'Client')], max_length=64, null=True, verbose_name='Категория пользователя'),
        ),
    ]
