FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# AliDentCRM

AliDent is a stomatology clinic

## Users Registration [/crm/users/]


### Register a New User [POST]

+ Request (application/json)

     + Headers
    
            Location: /rest-auth/registration/
    
    + Body

            [
                 {
                    "username": "0129234343557",
                    "email": "doasdasdccom@mail.ru",
                    "password": "Admin12345678",
                    "password2": "Admin12345678",
                    "name": "Санжар",
                    "surname": "Абдылдаев",
                    "patronymic": "Уланбекович",
                    "birthday": "2020-04-13",
                    "category": "Клиент"
                }
            ]

+ Response 201 (application/json)

    + Headers

            Location: /crm/users/

    + Body

            {
                "response": "Successfully registered a new user",
                "email": "doasdasdccom@mail.ru",
                "username": "0129234343557",
                "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MTAsImV4cCI6MTU5MjcxNzEyMn0.Ibm60gpJyJijdfYBkfCcM7k1Vxw5a0ic8GiK6IkLrPA"
            }



## Staff collection [/crm/staff/]

### List All Staff [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: /crm/staff/
            
    + Body

            [
                {
                    "id": 1,
                    "name": "Alexis Sanchez Sanchez",
                    "phone": "0999129557",
                    "birthday": "1998-11-10",
                    "email": "doc@mail.ru",
                    "experience": 3,
                    "specialization": "Удаление зубов"
                }
            ]



## Clients collection [/crm/clients/]

### List All Staff [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: /crm/clients/
            
    + Body

            [
                {
                    "id": 1,
                    "name": "Alexis Sanchez Sanchez",
                    "phone": "0999129557",
                    "birthday": "2020-04-04",
                    "email": "kingdoom_98@mail.ru"
                }
            ]



## User login [/crm/login/]

### Login [POST]
+ Request (application/json)

    + Headers
    
            Location: /crm/login/
    
    + Body

            [
                {
                    "username": "0559129557",
                    "password": "Admin123"
                }
            ]
            
+ Response 200 (application/json)

    + Headers
    
            Location: /crm/login/
            
    + Body

            [
                {
                    "username": "0559129557",
                    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNTkzMDgwNTk4fQ.9zGsY3Q3zHTW8u5ojo95fDTpl0R6DHkXtQfOhR211lk",
                    "is_staff": true
                }
            ]

        

## Service Category Collection [/crm/service-categories/]

### List All Service-Categories [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: /crm/service-categories/
            
    + Body

            [
                {
                    "id": 1,
                    "name": "Удаление",
                }
            ]



## Service Collection [/crm/services/]

### List All Services [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: /crm/services/
            
    + Body

            [
                {
                    "category": {
                        "id": 1,
                        "name": "Анестезия"
                    },
                    "code": 1.1,
                    "name": "Анестезия верхней челюсти",
                    "price": "1000.00"
                }
            ]




## Stocks Collection [/crm/stocks/]

### List All Stocks [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: api/stocks/
            
    + Body

            [
                {
                    "id": 1,
                    "service": {
                        "category": {
                            "id": 1,
                            "name": "Анестезия"
                        },
                        "code": 1.1,
                        "name": "Анестезия верхней челюсти",
                        "price": "1000.00"
                    },
                    "percentage": 10
                }
            ]
            

### Create a New Stock [POST]

+ Request (application/json)

        {
            "service": 1,
            "percentage": 15
        }

+ Response 201 (application/json)

    + Headers

            Location: /crm/stock/1

    + Body

            {
                "service": 1,
                "percentage": 15
            }


## Work Days Collection [/crm/days/]

### List All Days [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: /crm/days/
            
    + Body

            [
                {
                    "day": "Понедельник"
                }
            ]

### Create a New Day [POST]

+ Request (application/json)

        {
            "day": "Понедельник"
        }

+ Response 201 (application/json)

    + Headers

            Location: /crm/day/1

    + Body
    
            [    
                {  
                    "id": 1,
                    "day": "Понедельник"
                }
            ]



## Appointments [/api/appointments/]

### List All Appointments [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: /crm/appointments/
            
    + Body

            [
                {
                    "name": "Алекей",
                    "surname": "Чирков",
                    "time": "2020-04-05T18:47:42+06:00",
                    "phone": "0559129557",
                    "doctor": {
                        "id": 1,
                        "name": "Алекей Чирков Николаевич",
                        "phone": "0559129557",
                        "birthday": "2020-04-05",
                        "email": "tektonik_boy98@mail.ru"
                    },
                    "service": {
                        "category": {
                            "id": 1,
                            "name": "Анестезия"
                        },
                        "code": 1.1,
                        "name": "Анестезия верхней челюсти",
                        "price": "500.00"
                    },
                    "status": "Завершен"
                }
            ]



### Create Appointmnet [POST]
+ Request (application/json)

    + Headers
    
            Location: /crm/appointments/
    
    + Body

            [
                {
                    "name": "Евгений",
                    "surname": "Киселев",
                    "time": "2020-03-05T11:30:06+06:00",
                    "doctor": 1,
                    "service": 1,
                    "status": "Активен"
                }
            ]
            
+ Response 200 (application/json)

    + Headers
    
            Location: /crm/appointments/1
            
    + Body

            [
                {
                    "name": "Алекей",
                    "surname": "Чирков",
                    "time": "2020-03-12T18:00:00+06:00",
                    "doctor": 1,
                    "service": 1,
                    "status": "Активен"
                }
            ]   




## Statuses Collection [/crm/status/]

### List All Statuses [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: /crm/statuses/
            
    + Body

            [
                {
                    "id": 1,
                    "status": "Активен"
                }
            ]
            

### Create a New Status [POST]

+ Request (application/json)

        {
            "status": "Активен"
        }

+ Response 201 (application/json)

    + Headers

            Location: /crm/statuses/1

    + Body

            {
                "id": 1,
                "status": "Активен"
            }




## Expense Collection [/crm/expenses/]

### List All Expenses [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: /crm/expenses/
            
    + Body

            [
                {
                    "id": 1,
                    "service": {
                        "category": {
                            "id": 1,
                            "name": "Анестезия"
                        },
                        "code": 1.1,
                        "name": "Анестезия верхней челюсти",
                        "price": "1000.00"
                    },
                    "name": "Анестетик",
                    "category": "Препараты",
                    "description": "Описание",
                    "price": "200.00",
                    "date": "1998-11-10"
                }
            ]
            

### Create a New Expense [POST]

+ Request (application/json)

        {
            "name": "Анестетик",
            "category": "Препараты",
            "description": "Описание",
            "price": "200.00",
            "date": "1998-11-10",
            "service": 1
        }

+ Response 201 (application/json)

    + Headers

            Location: /crm/expenses/1

    + Body

            {
                "id": 1,
                "name": "Анестетик",
                "category": "Препараты",
                "description": "Описание",
                "price": "200.00",
                "date": "1998-11-10",
                "service": 1
            }



## Report Collection [/crm/reports/]

### List All Reports [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: /crm/reports/
            
    + Body

            [
                {
                    "id": 4,
                    "service": {
                        "category": {
                            "id": 1,
                            "name": "Анестезия"
                        },
                        "code": 1.1,
                        "name": "Анестезия верхней челюсти",
                        "price": "1000.00"
                    },
                    "count": 1,
                    "price": "1000.00",
                    "date": "2020-04-04"
                }
            ]



## Report Filters [/crm/reports/?search=2020-04-05]

### Search Reports With Date [GET]

+ Response 200 (application/json)
    
   + Headers

            Location: /crm/reports/?search=2020-04-05

   + Body
   
            [
                {
                    "id": 1,
                    "service": {
                        "category": {
                            "id": 1,
                            "name": "Анестезия"
                        },
                        "code": 1.1,
                        "name": "Анестезия верхней челюсти",
                        "price": "500.00"
                    },
                    "count": 7,
                    "price": "3500.00",
                    "date": "2020-04-05"
                }
            ]


## Income Collection [/crm/incomes/]

### List All Incomes [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: /crm/incomes/
            
    + Body

            [
                {
                    "id": 1,
                    "finished": 4,
                    "canceled": 2,
                    "amount": "2000.00",
                    "expense": "700.00",
                    "ratio": "1300.00",
                    "clients": 4,
                    "avg_cheque": "500.00",
                    "stocks": "150.00"
                }
            ]