FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# AliDentCRM

AliDent is a stomatology clinic

## Users collection [/crm/users/]

### List All Users [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: /crm/users/
            
    + Body

            [
                {
                    "id": 1,
                    "last_login": "2020-02-23T19:24:03.365819+06:00",
                    "name": "",
                    "surname": "",
                    "patronymic": "",
                    "birthday": null,
                    "phone": "0559129557",
                    "email": "tektonik_boy98@mail.ru",
                    "category": null
                }
            ]

### Register a New User [POST]

+ Request (application/json)

     + Headers
    
            Location: /rest-auth/registration/
    
    + Body

            [
                {
                    "username": "0559129557",
                    "email": "tektonik_boy98@mail.ru",
                    "password1": "Aleksissanchez98",
                    "password2": "Aleksissanchez98"
                }
            ]

+ Response 201 (application/json)

    + Headers

            Location: /crm/users/

    + Body

            {
                "username": "0559129557",
                "email": "tektonik_boy98@mail.ru",
                "name": null,
                "surname": null,
                "patronymic": null,
                "birthday": null
            }



## Staff collection [/crm/staff/]

### List All Staff [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: /crm/staff/
            
    + Body

            [
                {
                    "id": 1,
                    "name": "Alexis Sanchez Sanchez",
                    "phone": "0999129557",
                    "birthday": "1998-11-10",
                    "email": "doc@mail.ru"
                }
            ]



## User login [/rest-auth/login/]

### Login [POST]
+ Request (application/json)

    + Headers
    
            Location: /rest-auth/login/
    
    + Body

            [
                {
                    "username": "0559129557",
                    "email": "tektonik_boy98@mail.ru"
                    "password": "Aleksissanchez98"
                }
            ]
            
+ Response 200 (application/json)

    + Headers
    
            Location: /rest-auth/login/
            
    + Body

            [
                {
                    "username": "0559129557",
                    "email": "tektonik_boy98@mail.ru"
                    "password": "Aleksissanchez98"
                }
            ]
        
        
        
## Appointments [/api/appointments/]

### List All Appointments [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: /crm/appointments/
            
    + Body

            [
                {
                    "name": "Алекей",
                    "surname": "Чирков",
                    "time": "2020-03-12T18:00:00+06:00",
                    "doctor": {
                        "id": 1,
                        "name": "Alexis Sanchez Sanchez",
                        "phone": "0999129557",
                        "birthday": "1998-11-10",
                        "email": "doc@mail.ru"
                    },
                    "service": {
                        "code": 1.1,
                        "name": "Анестезия верхней челюсти",
                        "price": "1000.00",
                        "category": 1
                    },
                    "status": "Активен"
                }
            ]

### Create Appointmnet [POST]
+ Request (application/json)

    + Headers
    
            Location: /crm/appointments/
    
    + Body

            [
                {
                    "name": "Евгений",
                    "surname": "Киселев",
                    "time": "2020-03-05T11:30:06+06:00",
                    "doctor": 1,
                    "status": "Активен"
                    "service": 1,
                }
            ]
            
+ Response 200 (application/json)

    + Headers
    
            Location: /crm/appointments/1
            
    + Body

            [
                {
                    "name": "Алекей",
                    "surname": "Чирков",
                    "time": "2020-03-12T18:00:00+06:00",
                    "doctor": 1,
                    "service": 1,
                    "status": "Активен"
                }
            ]


        

## Service Category Collection [/crm/service-categories/]

### List All Service-Categories [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: /crm/service-categories/
            
    + Body

            [
                {
                    "id": 1,
                    "name": "Удаление",
                }
            ]



## Service Collection [/crm/services/]

### List All Services [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: /crm/services/
            
    + Body

            [
                {
                    {
                        "id": 1,
                        "code": 1.1,
                        "name": "Удаление коренного зуба",
                        "price": "2000.00"
                        "category": 1
                    }
                }
            ]
            


## Work Days Collection [/crm/days/]

### List All Days [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: /crm/days/
            
    + Body

            [
                {
                    "day": "Понедельник"
                }
            ]



## Stocks Collection [/crm/stocks/]

### List All Stocks [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: api/stocks/
            
    + Body

            [
                {
                    "id": 1,
                    "service": {
                        "id": 1,
                        "category": {
                            "id": 1,
                            "name": "Удаление"
                        },
                        "code": 1.1,
                        "name": "Удаление коренного зуба",
                        "price": "2000.00"
                    },
                    "percentage": 15
                }
            ]
            

### Create a New Stock [POST]

+ Request (application/json)

        {
            "service": {
                "id": 1,
                "category": {
                    "id": 1,
                    "name": "Удаление"
                },
                "code": 1.1,
                "name": "Удаление коренного зуба",
                "price": "2000.00"
            },
            "percentage": 15
        }

+ Response 201 (application/json)

    + Headers

            Location: /crm/stock/1

    + Body

            {
                "id": 1,
                "service": {
                    "id": 1,
                    "category": {
                        "id": 1,
                        "name": "Удаление"
                    },
                    "code": 1.1,
                    "name": "Удаление коренного зуба",
                    "price": "2000.00"
                },
                "percentage": 15
            }
            


## Statuses Collection [/crm/status/]

### List All Statuses [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: /crm/statuses/
            
    + Body

            [
                {
                    "id": 1,
                    "status": "Активен"
                }
            ]
            

### Create a New Status [POST]

+ Request (application/json)

        {
            "status": "Активен"
        }

+ Response 201 (application/json)

    + Headers

            Location: /crm/statuses/1

    + Body

            {
                "id": 1,
                "status": "Активен"
            }