FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# AliDentCRM

AliDent is a stomatology clinic

## Users collection [/api/users/]

### List All Users [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: /api/users/
            
    + Body

            [
                {
                    "id": 1,
                    "last_login": "2020-02-23T19:24:03.365819+06:00",
                    "name": "",
                    "surname": "",
                    "patronymic": "",
                    "birthday": null,
                    "phone": "0559129557",
                    "email": "tektonik_boy98@mail.ru",
                    "category": null
                }
            ]

### Register a New User [POST]

+ Request (application/json)

     + Headers
    
            Location: /rest-auth/registration/
    
    + Body

            [
                {
                    "username": "0559129557",
                    "email": "tektonik_boy98@mail.ru",
                    "password1": "Aleksissanchez98",
                    "password2": "Aleksissanchez98"
                }
            ]

+ Response 201 (application/json)

    + Headers

            Location: api/users/

    + Body

            {
                "username": "0559129557",
                "email": "tektonik_boy98@mail.ru",
                "name": null,
                "surname": null,
                "patronymic": null,
                "birthday": null
            }
            
## User login [/rest-auth/login/]

### List All Categories [POST]
+ Request (application/json)

    + Headers
    
            Location: /rest-auth/login/
    
    + Body

            [
                {
                    "username": "0559129557",
                    "email": "tektonik_boy98@mail.ru"
                    "password": "Aleksissanchez98"
                }
            ]
            
+ Response 200 (application/json)

    + Headers
    
            Location: /rest-auth/login/
            
    + Body

            [
                {
                    "username": "0559129557",
                    "email": "tektonik_boy98@mail.ru"
                    "password": "Aleksissanchez98"
                }
            ]
        
        
        
## Appointments [/api/appointments/]

### List All Users [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: /api/appointments/
            
    + Body

            [
                {
                    "name": "Евгений",
                    "surname": "Киселев",
                    "time": "2020-03-05T11:30:06+06:00",
                    "doctor": {
                        "id": 1,
                        "staff": {
                            "username": "0559129557",
                            "email": "tektonik_boy98@mail.ru",
                            "name": null,
                            "surname": null,
                            "patronymic": null,
                            "birthday": null
                        }
                    },
                    "status": {
                        "id": 1,
                        "status": "Активен"
                    },
                    "service": {
                        "id": 1,
                        "category": {
                            "id": 1,
                            "name": "Удаление"
                        },
                        "code": 1.1,
                        "name": "Удаление коренного зуба",
                        "price": "2000.00"
                    }
                }
            ]

### List All Appointments [POST]
+ Request (application/json)

    + Headers
    
            Location: /api/appointments/
    
    + Body

            [
                {
                    "name": "Евгений",
                    "surname": "Киселев",
                    "time": "2020-03-05T11:30:06+06:00",
                    "doctor": {
                        "id": 1,
                        "staff": {
                            "username": "0559129557",
                            "email": "tektonik_boy98@mail.ru",
                            "name": null,
                            "surname": null,
                            "patronymic": null,
                            "birthday": null
                        }
                    },
                    "status": {
                        "id": 1,
                        "status": "Активен"
                    },
                    "service": {
                        "id": 1,
                        "category": {
                            "id": 1,
                            "name": "Удаление"
                        },
                        "code": 1.1,
                        "name": "Удаление коренного зуба",
                        "price": "2000.00"
                    }
                }
            ]
            
+ Response 200 (application/json)

    + Headers
    
            Location: /api/appointments/1
            
    + Body

            [
                {
                    "name": "Евгений",
                    "surname": "Киселев",
                    "time": "2020-03-05T11:30:06+06:00",
                    "doctor": {
                        "id": 1,
                        "staff": {
                            "username": "0559129557",
                            "email": "tektonik_boy98@mail.ru",
                            "name": null,
                            "surname": null,
                            "patronymic": null,
                            "birthday": null
                        }
                    },
                    "status": {
                        "id": 1,
                        "status": "Активен"
                    },
                    "service": {
                        "id": 1,
                        "category": {
                            "id": 1,
                            "name": "Удаление"
                        },
                        "code": 1.1,
                        "name": "Удаление коренного зуба",
                        "price": "2000.00"
                    }
                }
            ]
        
        
        
           
## Users-Categories Collection [/api/users-categories/]

### List All Categories [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: api/users-categories/
            
    + Body

            [
                {
                    "id": 2,
                    "name": "Врач",
                }
            ]

### Create a New User-Category [POST]

+ Request (application/json)

        {
            "name": "Врач",
        }

+ Response 201 (application/json)

    + Headers

            Location: api/users-categories/2

    + Body

            {
                "id": 2,
                "name": "Врач",
            }
            
            

## Service Category Collection [/api/service-categories/]

### List All Service-Categories [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: api/service-categories/
            
    + Body

            [
                {
                    "id": 1,
                    "name": "Удаление",
                }
            ]

### Create a New Service-Category [POST]

+ Request (application/json)

        {
            "name": "Удаление",
        }

+ Response 201 (application/json)

    + Headers

            Location: api/service-categories/2

    + Body

            {
                "id": 2,
                "name": "Удаление",
            }


## Service Collection [/api/services/]

### List All Services [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: api/services/
            
    + Body

            [
                {
                    {
                        "id": 1,
                        "category": {
                            "id": 1,
                            "name": "Удаление"
                        },
                        "code": 1.1,
                        "name": "Удаление коренного зуба",
                        "price": "2000.00"
                    }
                }
            ]
            

### Create a New Service [POST]

+ Request (application/json)

        {
            {
                "id": 1,
                "category": {
                    "id": 1,
                    "name": "Удаление"
                },
                "code": 1.1,
                "name": "Удаление коренного зуба",
                "price": "2000.00"
            }
        }

+ Response 201 (application/json)

    + Headers

            Location: api/services/1

    + Body

            {
                {
                    "id": 1,
                    "category": {
                        "id": 1,
                        "name": "Удаление"
                    },
                    "code": 1.1,
                    "name": "Удаление коренного зуба",
                    "price": "2000.00"
                }
            }
            
            

## Work Days Collection [/api/days/]

### List All Days [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: api/days/
            
    + Body

            [
                {
                    "day": "Понедельник"
                }
            ]
            

### Create a New Days [POST]

+ Request (application/json)

        {
            "day": "Понедельник"
        }

+ Response 201 (application/json)

    + Headers

            Location: api/days/1

    + Body

            {
                "day": "Понедельник"
            }
            
            
            
## Stocks Collection [/api/stocks/]

### List All Stocks [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: api/stocks/
            
    + Body

            [
                {
                    "id": 1,
                    "service": {
                        "id": 1,
                        "category": {
                            "id": 1,
                            "name": "Удаление"
                        },
                        "code": 1.1,
                        "name": "Удаление коренного зуба",
                        "price": "2000.00"
                    },
                    "percentage": 15
                }
            ]
            

### Create a New Stock [POST]

+ Request (application/json)

        {
            "service": {
                "id": 1,
                "category": {
                    "id": 1,
                    "name": "Удаление"
                },
                "code": 1.1,
                "name": "Удаление коренного зуба",
                "price": "2000.00"
            },
            "percentage": 15
        }

+ Response 201 (application/json)

    + Headers

            Location: api/stock/1

    + Body

            {
                "id": 1,
                "service": {
                    "id": 1,
                    "category": {
                        "id": 1,
                        "name": "Удаление"
                    },
                    "code": 1.1,
                    "name": "Удаление коренного зуба",
                    "price": "2000.00"
                },
                "percentage": 15
            }
            


## Statuses Collection [/api/status/]

### List All Statuses [GET]

+ Response 200 (application/json)

    + Headers
    
            Location: api/statuses/
            
    + Body

            [
                {
                    "id": 1,
                    "status": "Активен"
                }
            ]
            

### Create a New Status [POST]

+ Request (application/json)

        {
            "status": "Активен"
        }

+ Response 201 (application/json)

    + Headers

            Location: api/statuses/1

    + Body

            {
                "id": 1,
                "status": "Активен"
            }