# Generated by Django 3.0 on 2020-05-22 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Ф.И.О.')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.IntegerField(default=0, verbose_name='Завершенных записей')),
                ('canceled', models.IntegerField(default=0, verbose_name='Отмененных записей')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий доход')),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий расход')),
                ('ratio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Соотношение доход/расход')),
                ('avg_cheque', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Средний чек')),
                ('clients', models.IntegerField(default=0, verbose_name='Новых клиентов')),
                ('stocks', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидок на сумму')),
                ('amount_stocks', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доход с учетом скидок')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата отчета')),
            ],
            options={
                'verbose_name': 'Отчет за день',
                'verbose_name_plural': 'Отчеты по дням',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=16, verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Рабочий день',
                'verbose_name_plural': 'Рабочие дни',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.IntegerField(default=0, verbose_name='Завершенных записей')),
                ('canceled', models.IntegerField(default=0, verbose_name='Отмененных записей')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий доход')),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий расход')),
                ('ratio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Соотношение')),
                ('clients', models.IntegerField(default=0, verbose_name='Всего клиентов')),
                ('avg_cheque', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Средний чек')),
                ('stocks', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидок на сумму')),
                ('amount_stocks', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доход с учетом скидок')),
            ],
            options={
                'verbose_name': 'Доход',
                'verbose_name_plural': 'Доходы',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Ф.И.О.')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('experience', models.IntegerField(blank=True, default=0, null=True, verbose_name='Опыт работы')),
                ('specialization', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Специализация')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=256, verbose_name='Описание')),
                ('percentage', models.IntegerField(verbose_name='Скидка в %')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Кодировка')),
                ('name', models.CharField(max_length=128, verbose_name='Услуга')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.ServiceCategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Записей за день')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата отчета')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Service', verbose_name='Название услуги')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('category', models.CharField(max_length=64, verbose_name='Категория расхода')),
                ('description', models.CharField(max_length=128, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость (сом)')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=128, verbose_name='Клиент')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата чека')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Service', verbose_name='Услуга')),
                ('stock', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Stock', verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=64, verbose_name='Телефон клиента')),
                ('time', models.DateTimeField(help_text='Формат: ', null=True, verbose_name='Время')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('Активен', 'Активен'), ('Завершен', 'Завершен'), ('Приостановлен', 'Приостановлен'), ('Отменен', 'Отменен')], default='Активен', max_length=64, verbose_name='Статус')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('appointment_income', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Income', verbose_name='Доход с записи')),
                ('doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.Staff', verbose_name='Врач')),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.Service', verbose_name='Услуга')),
                ('stock', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Stock', verbose_name='Акция')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
