# Generated by Django 3.0 on 2020-04-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialization',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Специализация'),
        ),
    ]
