# Generated by Django 3.0 on 2020-04-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Общий доход'),
        ),
        migrations.AlterField(
            model_name='income',
            name='canceled',
            field=models.IntegerField(default=0, null=True, verbose_name='Отмененных записей'),
        ),
        migrations.AlterField(
            model_name='income',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Общий расход'),
        ),
        migrations.AlterField(
            model_name='income',
            name='finished',
            field=models.IntegerField(default=0, null=True, verbose_name='Завершенных записей'),
        ),
        migrations.AlterField(
            model_name='income',
            name='ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Соотношение'),
        ),
    ]
