# Generated by Django 3.0 on 2020-05-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='clients',
            field=models.IntegerField(default=0, verbose_name='Новых клиентов'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Соотношение доход/расход'),
        ),
    ]
