# Generated by Django 3.0 on 2020-03-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='work_time',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Режим работы'),
        ),
    ]
