# Generated by Django 3.0 on 2020-05-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='amount_stocks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доход с учетом скидок'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='stocks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидок на сумму'),
        ),
    ]
