# Generated by Django 3.0 on 2020-04-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='new_clients',
            field=models.IntegerField(default=0, verbose_name='Новых клиентов'),
        ),
    ]
