# Generated by Django 3.0 on 2020-05-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(max_length=32, verbose_name='Кодировка'),
        ),
    ]
