# Generated by Django 3.0 on 2020-02-24 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_income',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.Income', verbose_name='Доход с записи'),
        ),
        migrations.AlterField(
            model_name='income',
            name='cheque',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.Appointment', verbose_name='Чек'),
        ),
    ]
