# Generated by Django 3.0 on 2020-06-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Услуга'),
        ),
    ]
