# Generated by Django 3.0 on 2020-03-10 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Персонал'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.ServiceCategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='income',
            name='cheque',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Appointment', verbose_name='Чек'),
        ),
        migrations.AddField(
            model_name='expense',
            name='service',
            field=models.ManyToManyField(default=None, to='crm.Service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='appointment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.Appointment', verbose_name='Запись'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.Service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='stock',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Stock', verbose_name='Акция'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_income',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Income', verbose_name='Доход с записи'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.Staff'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.Service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.Stage', verbose_name='Статус'),
        ),
    ]
