# Generated by Django 3.0 on 2020-02-24 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20200224_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_income',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Income', verbose_name='Доход с записи'),
        ),
    ]
