# Generated by Django 3.0 on 2020-11-05 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20200626_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
