# Generated by Django 3.0 on 2020-03-19 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20200319_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.Staff', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Активен', 'Активен'), ('Завершен', 'Завершен'), ('Приостановлен', 'Приостановлен')], max_length=64, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
