# Generated by Django 3.0 on 2020-04-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_income_new_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='new_clients',
        ),
        migrations.AddField(
            model_name='income',
            name='clients',
            field=models.IntegerField(default=0, verbose_name='Всего клиентов'),
        ),
    ]
