# Generated by Django 3.0 on 2020-05-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20200508_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(help_text='Формат: ', null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кодировка'),
        ),
    ]
