# Generated by Django 3.0 on 2020-11-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_delete_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание врача'),
        ),
    ]
