# Generated by Django 3.0 on 2020-05-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20200521_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Кодировка'),
        ),
    ]
