# Generated by Django 3.0 on 2020-04-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20200405_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='avg_cheque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Средний чек'),
        ),
    ]
