# Generated by Django 3.0 on 2020-04-07 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_income_avg_cheque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='service',
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Цена')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Client', verbose_name='Клиент')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Service', verbose_name='Услуга')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Stock', verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
    ]
