# Generated by Django 3.0 on 2020-11-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20201105_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Отчет по услуге', 'verbose_name_plural': 'Отчеты по услугам'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='report',
            name='count',
            field=models.IntegerField(verbose_name='Записей за месяц'),
        ),
    ]
