# Generated by Django 3.0 on 2020-04-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cheque',
        ),
    ]
