# Generated by Django 3.0 on 2020-05-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20200521_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.FloatField(verbose_name='Кодировка'),
        ),
    ]
