# Generated by Django 3.0 on 2020-05-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20200521_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='Кодировка'),
        ),
    ]
