# Generated by Django 3.0 on 2020-11-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20201107_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='amount_stocks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Чистая прибыль'),
        ),
    ]
