# Generated by Django 3.0 on 2020-11-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20201105_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
