# Generated by Django 3.0 on 2020-04-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20200407_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
