# Generated by Django 3.0 on 2020-11-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_appointment_is_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='is_added',
            field=models.BooleanField(default=False, verbose_name='Добавлено в отчет'),
        ),
    ]
