# Generated by Django 3.0 on 2020-04-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20200407_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
