# Generated by Django 3.0 on 2020-11-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20201105_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='amount_stocks',
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Чистая прибыль'),
        ),
    ]
