# Generated by Django 3.0 on 2020-04-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20200407_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка'),
        ),
    ]
