# Generated by Django 3.0 on 2020-11-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20201106_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='amount_stocks',
        ),
        migrations.AlterField(
            model_name='income',
            name='ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Чистая прибыль'),
        ),
    ]
